name: Create and Push Docker Image CI (GHCR)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write    # ✅ allows pushing to GHCR
  id-token: write    # (optional for OIDC / provenance)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: repo_owner
        run: echo "repo_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_owner.outputs.repo_owner }}/my-imagename:latest
            ghcr.io/${{ steps.repo_owner.outputs.repo_owner }}/my-imagename:${{ github.run_number }}
            ghcr.io/${{ steps.repo_owner.outputs.repo_owner }}/my-imagename:${{ github.sha }}

      - name: Verify image
        run: docker pull ghcr.io/${{ steps.repo_owner.outputs.repo_owner }}/my-imagename:latest
